SELECT H.*, IFNULL(C.COUNT, 0) AS COUNT
FROM (
    SELECT '00' AS HOUR UNION
    SELECT '01' AS HOUR UNION
    SELECT '02' AS HOUR UNION
    SELECT '03' AS HOUR UNION
    SELECT '04' AS HOUR UNION
    SELECT '05' AS HOUR UNION
    SELECT '06' AS HOUR UNION
    SELECT '07' AS HOUR UNION
    SELECT '08' AS HOUR UNION
    SELECT '09' AS HOUR UNION
    SELECT '10' AS HOUR UNION
    SELECT '11' AS HOUR UNION
    SELECT '12' AS HOUR UNION
    SELECT '13' AS HOUR UNION
    SELECT '14' AS HOUR UNION
    SELECT '15' AS HOUR UNION
    SELECT '16' AS HOUR UNION
    SELECT '17' AS HOUR UNION
    SELECT '18' AS HOUR UNION
    SELECT '19' AS HOUR UNION
    SELECT '20' AS HOUR UNION
    SELECT '21' AS HOUR UNION
    SELECT '22' AS HOUR UNION
    SELECT '23' AS HOUR
  ) AS H
LEFT JOIN(
    SELECT SUBSTR(DATETIME, 12, 2) AS HOUR, COUNT(DATETIME) AS COUNT
    FROM ANIMAL_OUTS
    GROUP BY HOUR
    ORDER BY HOUR) AS C
ON H.HOUR = C.HOUR;
